### ISSUE TITLE
用户评分生成优化

### ISSUE THREAD

**Issue by lblinm** [lblinm/work_together#2]
**问题**：
1. 当前评分生成比较粗糙，每个用户是[0,9]之间的随机整数，导致预测评分时差距不够大，排序后的推荐结果集中在id小的视频
3. 评分生成过于单调，只是随机数，没有体现用户、视频之间的差异，用户和视频之间没有联系
4. 用户评分行为没有体现时间性，无法提供视频热度预测的数据
**思路(仅我自己而言，请发挥你们的创造力😘)**：
1. 增加用户评分的差距，采用[0,10]之间的随机整数
2. 体现用户差异：不同用户具有不同特征，如评分服从均匀分布还是正态分布，评分整体是苛刻还是宽松
5. 体现视频差异：不仅以用户为主体评分，也可以以视频为主体评分，不同视频评分整体不同，体现视频之间的质量差异
6. 选择：另外模拟生成视频观看的时间序列，具体可以是
    |vid|day|play|
    |---|---|---|
    |视频id|日期|播放量|
7. 选择：生成集中了时间序列和用户评分的数据

**Comment by MYS109hqj** [comment]
目前：能够使用numpy以指定的正态分布参数生成四种评分风格的评分。
输入：调用对应风格函数（函数未命名，也可用一个参数区分），生成的初始评分数量。可选择传入微调量（以调整均值或标准差）（未实现但可实现）
输出：在[0,5]范围内的指定数量的浮点数（以浮点数进行后续系数处理）

**Comment by MYS109hqj** [comment]
目前优化方向主要就是pandas的访存
完全at访存，cum time>10s的项目（选取自cProfile的输出）
        1    0.002    0.002  417.146  417.146 <string>:1(<module>)
 41232135   68.368    0.000  196.295    0.000 frame.py:4191(_get_value)
 41232135   34.373    0.000   60.112    0.000 frame.py:4626(_get_item_cache)
 41232135   47.280    0.000  256.206    0.000 indexing.py:2518(__getitem__)
 41232135   50.117    0.000  345.270    0.000 indexing.py:2568(__getitem__)
 41232145   10.091    0.000   10.091    0.000 managers.py:2004(internal_values)
 41232135   25.275    0.000   37.133    0.000 range.py:408(get_loc)
 41232145   14.350    0.000   24.441    0.000 series.py:831(_values)
      1    0.000    0.000  417.146  417.146 {built-in method builtins.exec}
82465158/82465156   11.047    0.000   11.047    0.000 {built-in method builtins.isinstance}
  1992996   10.209    0.000   10.209    0.000 {built-in method builtins.round}
 41232135   11.857    0.000   11.857    0.000 {method 'index' of 'range' objects}
